/*
 * aboutForm.java
 *
 * @author Marcus Wynwood
 */

package duplifinder;

public class aboutForm extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form aboutForm */
    public aboutForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        licenceButton = new javax.swing.JButton();
        pictureLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setTitle("About dupliFinder");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/emblem-gear.png")));
        okButton.setText("OK");
        okButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        licenceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gnome-application-rtf.png")));
        licenceButton.setText("Licence Info...");
        licenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenceButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(licenceButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pictureLabel.setBackground(java.awt.Color.white);
        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/piereceTriplets.jpg")));
        pictureLabel.setToolTipText("The Pierce Triplets");
        pictureLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(pictureLabel, java.awt.BorderLayout.EAST);

        jScrollPane1.setBorder(null);
        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setText("by Marcus Wynwood\n\ndupliFinder lets you search your computer for duplicate files by creating and comparing a unique fingerprint of each file. This means that even if the files have different names, dupliFinder will still recignise them as duplicates. This is great for searching your MP3 collection, your movie collection, a collection of images, or any other group of files.\n\nAll you need to do to use dupliFinder is browse to select a folder and clicked \"Find Duplicates\". You will then get a list of duplicate files along with the file that they match up too. The original file is always the \"shallowest\" on the file system. If you are using a Unix based OS be careful because dupliFinder doesn't understand symbolic links.\n\ndupliFinder started as a small Linux bash script so I could remove duplicates from my MP3 collection. I made it because I couldn't find any other software that did this. Some of my non-Linux friends saw the script and asked if I could make a Windows version for them. So, I started creating dupliFinder in Java.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setText("dupliFinder");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void licenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenceButtonActionPerformed
        if (javax.swing.JOptionPane.showConfirmDialog(null,
        "dupliFinder is free software released under the GNU General Public License\n" +
        "dupliFinder is Copyright Marcus Wynwood.\n\n" +
        "This software contains some code from other free or open source projects:\n\n" +
        "   * JigSaw, the W3C's open source implementation of a\n" +
        "     Java web server (http://www.w3.org/Jigsaw/)\n\n" +
        "   * An example on recursivly listing files in Java by Alex Wong\n" +
        "     (http://www.javapractices.com/Topic68.cjp)\n\n" +
        "   * An example on loading the default browser by Steven Spencer.\n" +
        "     (http://www.javaworld.com/javaworld/javatips/jw-javatip66.html)\n\n" +
        "   * The icons are from my '/usr/share/pixmaps/' directory ;-)\n\n" +

        "Do you want to view the GNU General Public License?", "Licence Info",
        //1
        javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE
        )==0) {
            // User clicks Yes:
            // A local version would be better
            browserControl browser = new browserControl();
            browser.displayURL("http://www.gnu.org/licenses/gpl.txt");
        } else {
            // User clicks No:
        }
    }//GEN-LAST:event_licenceButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
        
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutForm(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton licenceButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pictureLabel;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}